### ISSUE TITLE
RequestCorrelationUtils.getCurrentCorrelationId()

### ISSUE THREAD

**Issue by FranPregernik** [jmnarloch/request-correlation-spring-cloud-starter#2]
Hi,

I might not be using this correctly but ClientHttpRequestCorrelationInterceptor is using the `RequestCorrelationUtils.getCurrentCorrelationId()` and that data is not set.

I verified by debugging that RequestCorrelationFilter was called, and that enhanceRequest sets the autogenerated correlation id. But anywhere else in the call stack of the next filters RequestCorrelationUtils.getCurrentCorrelationId() is null.

I see it uses the RequestContextHolder.getRequestAttributes but that returns an empty map.

When should the generated correlation id be set in the request attributes?

Br,
Fran

**Comment by FranPregernik** [comment]
I followed the instructions in the README and MDC receives the correlation id.

Do I need to create another one that fills in the RequestContextHolder?

**Comment by jmnarloch** [comment]
I think that I am lost from this description, so you can see the
correlationId set on the MDC, but when the RequestCorrelationUtils.
getCurrentCorrelationId() is being called you receive, null?

The typical setup doesn't require to do anything more then to have
spring-boot-starter-web and request-correlation-spring-cloud-starter on the
classpath.

In the Demo there is the test case that covers this use case
https://github.com/jmnarloch/request-correlation-spring-cloud-starter/blob/master/src/test/java/io/jmnarloch/spring/request/correlation/Demo.java#L127

2016-05-01 8:23 GMT+02:00 Fran Pregernik notifications@github.com:

**Comment by FranPregernik** [comment]
I apologize, writing issues that early in the morning .... should have read through it one more time.

Anyway.

I set a breakpoint in RequestCorrelationFilter just after this line:

``` java
        // populates the attribute
        final ServletRequest req = enrichRequest(request, requestCorrelation);
```

I see that the req has the additional field with the correlation id. 
I then added the getCurrentCorrelationId in the watch window and got null.
I then let the program run until my code was reached and there I see that MDC contains the correlationId as per your instructions. The getCurrentCorrelationId is still null.

What I neglected to mention the first time was that the code is in an `@Async` block. 
That could be it.

If that is the case, do you have any instructions how to propagate to the thread pool?

**Comment by jmnarloch** [comment]
OK, thanks for the clarification, the problem that you are facing is the fact that the code is being run is in separate thread, that is no longer bound to the request thread. 

Also if you can please check if the MDC contains the correct value the one either generated by the RequestCorrelationFilter or received from header, because it is quite likely that the MDC contains some stale value populated when the thread was created and that will remain there for ever.

Unfortunately handling the RestTemplate in @Async method is currently not supported, since the correlation is being stored as you have noticed in RequestContextHolder which is thread bound.

In theory you should be able to find a workaround for that by implementing your custom TaskExecutor like for instance ThreadPoolTaskExecutor, that wraps the Callable or Runable and populates that thread with a copy of RequestContextHolder.getRequestAttributes. That should work.

**Comment by FranPregernik** [comment]
Thank you for the explanation.

I will close the issue now.

Br,
Fran
